#line 1 "conffile.yy.c"

#line 3 "conffile.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define router_yy_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer router_yy_create_buffer
#endif

#ifdef yy_delete_buffer
#define router_yy_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer router_yy_delete_buffer
#endif

#ifdef yy_scan_buffer
#define router_yy_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer router_yy_scan_buffer
#endif

#ifdef yy_scan_string
#define router_yy_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string router_yy_scan_string
#endif

#ifdef yy_scan_bytes
#define router_yy_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes router_yy_scan_bytes
#endif

#ifdef yy_init_buffer
#define router_yy_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer router_yy_init_buffer
#endif

#ifdef yy_flush_buffer
#define router_yy_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer router_yy_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define router_yy_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state router_yy_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define router_yy_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer router_yy_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define router_yypush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state router_yypush_buffer_state
#endif

#ifdef yypop_buffer_state
#define router_yypop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state router_yypop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define router_yyensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack router_yyensure_buffer_stack
#endif

#ifdef yylex
#define router_yylex_ALREADY_DEFINED
#else
#define yylex router_yylex
#endif

#ifdef yyrestart
#define router_yyrestart_ALREADY_DEFINED
#else
#define yyrestart router_yyrestart
#endif

#ifdef yylex_init
#define router_yylex_init_ALREADY_DEFINED
#else
#define yylex_init router_yylex_init
#endif

#ifdef yylex_init_extra
#define router_yylex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra router_yylex_init_extra
#endif

#ifdef yylex_destroy
#define router_yylex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy router_yylex_destroy
#endif

#ifdef yyget_debug
#define router_yyget_debug_ALREADY_DEFINED
#else
#define yyget_debug router_yyget_debug
#endif

#ifdef yyset_debug
#define router_yyset_debug_ALREADY_DEFINED
#else
#define yyset_debug router_yyset_debug
#endif

#ifdef yyget_extra
#define router_yyget_extra_ALREADY_DEFINED
#else
#define yyget_extra router_yyget_extra
#endif

#ifdef yyset_extra
#define router_yyset_extra_ALREADY_DEFINED
#else
#define yyset_extra router_yyset_extra
#endif

#ifdef yyget_in
#define router_yyget_in_ALREADY_DEFINED
#else
#define yyget_in router_yyget_in
#endif

#ifdef yyset_in
#define router_yyset_in_ALREADY_DEFINED
#else
#define yyset_in router_yyset_in
#endif

#ifdef yyget_out
#define router_yyget_out_ALREADY_DEFINED
#else
#define yyget_out router_yyget_out
#endif

#ifdef yyset_out
#define router_yyset_out_ALREADY_DEFINED
#else
#define yyset_out router_yyset_out
#endif

#ifdef yyget_leng
#define router_yyget_leng_ALREADY_DEFINED
#else
#define yyget_leng router_yyget_leng
#endif

#ifdef yyget_text
#define router_yyget_text_ALREADY_DEFINED
#else
#define yyget_text router_yyget_text
#endif

#ifdef yyget_lineno
#define router_yyget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno router_yyget_lineno
#endif

#ifdef yyset_lineno
#define router_yyset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno router_yyset_lineno
#endif

#ifdef yyget_column
#define router_yyget_column_ALREADY_DEFINED
#else
#define yyget_column router_yyget_column
#endif

#ifdef yyset_column
#define router_yyset_column_ALREADY_DEFINED
#else
#define yyset_column router_yyset_column
#endif

#ifdef yywrap
#define router_yywrap_ALREADY_DEFINED
#else
#define yywrap router_yywrap
#endif

#ifdef yyget_lval
#define router_yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval router_yyget_lval
#endif

#ifdef yyset_lval
#define router_yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval router_yyset_lval
#endif

#ifdef yyalloc
#define router_yyalloc_ALREADY_DEFINED
#else
#define yyalloc router_yyalloc
#endif

#ifdef yyrealloc
#define router_yyrealloc_ALREADY_DEFINED
#else
#define yyrealloc router_yyrealloc
#endif

#ifdef yyfree
#define router_yyfree_ALREADY_DEFINED
#else
#define yyfree router_yyfree
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define router_yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 115
#define YY_END_OF_BUFFER 116
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[594] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  116,  114,
      109,  110,  114,  113,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  111,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  107,
      107,  105,  104,  107,  107,  114,  103,  112,  111,   26,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,

      112,   33,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  109,  110,    0,  108,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        5,    0,    0,    0,    0,    0,    0,   41,    0,    0,
      111,    0,   52,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   56,    0,    0,    0,    0,    0,   74,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  107,  107,  107,
      106,  112,  112,  111,  112,  112,  112,  112,   13,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,

      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   36,    0,    0,    0,    0,    0,    0,
        0,   68,    0,   62,    0,    0,   55,    0,   64,    0,
        0,   66,    0,    0,    0,    0,    0,   60,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  100,    0,   99,    0,    0,  112,
      112,  112,  112,  112,   23,  112,  112,  112,  112,   25,
      112,  112,   16,  112,  112,   30,  112,   15,  112,  112,

      112,  112,  112,  112,   95,  112,  112,  112,   97,  112,
        0,    0,    0,    0,    0,    0,   76,    0,    0,    0,
        0,   12,    0,    0,    0,   37,   35,    0,   40,   43,
        0,   45,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   75,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   88,
        0,   87,    0,    0,   90,  101,  112,  112,  112,  112,
       22,  112,  112,  112,  112,  112,   43,  112,  112,  112,
       17,  112,  112,   40,  112,  112,   94,  112,  112,  112,
      112,    0,    0,    0,    0,   32,    0,    0,    0,    0,

        0,    0,    0,    0,   38,   39,   50,    0,    0,    0,
       61,    0,    0,    0,    0,    0,    0,    0,   53,    0,
        0,    0,    0,   73,    0,   84,    0,   80,    0,    0,
       82,    0,    0,    0,   98,  112,  112,  112,  112,  112,
       21,   14,  112,  112,  112,  112,  112,  112,  112,   38,
      112,   47,   93,   98,  112,  112,    0,    0,    0,   89,
        0,    0,    3,    0,    0,    0,    0,    0,    0,   57,
        0,   49,    0,   69,   54,    0,    0,    0,   72,    0,
        0,    0,    0,    0,    0,   86,    0,   79,    0,  112,
      112,  112,  112,  112,   24,   19,  112,  112,  112,    6,

      112,   96,  112,    0,    1,  102,   44,    0,    0,    0,
        0,    2,    0,   67,   58,   63,   65,    0,   48,   59,
        0,    0,    0,    0,    0,   81,    0,  112,  112,   11,
      112,  112,   31,  112,  112,  112,  112,    0,    0,    0,
        4,    8,    0,    0,    0,   71,    0,   83,   85,   91,
      112,  112,   18,  112,  112,  112,   34,  112,   46,    0,
        7,    0,    0,   51,    0,   42,  112,  112,  112,   20,
       92,   78,    0,   70,   77,  112,  112,  112,    0,   70,
       27,   10,  112,  112,    0,  112,  112,    9,   29,  112,
      112,   28,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    7,    7,    7,    1,    7,
        7,    8,    7,    7,    7,    7,    7,    9,   10,    9,
        9,   11,    9,    9,    9,    9,    9,    7,   12,    7,
       13,    7,    7,    1,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,   14,    7,    7,   15,    1,   16,   17,   18,   19,

       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,    7,   32,   33,   34,   35,   36,   37,   38,
       39,   40,    7,    7,    7,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[41] =
    {   0,
        1,    1,    2,    1,    3,    1,    4,    4,    4,    4,
        4,    1,    1,    5,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4
    } ;

static const flex_int16_t yy_base[602] =
    {   0,
        0,   32,   50,    0,   68,    0,   88,   98,  117,    0,
        4,   24,  139,    0,  161,    0,  195,  208,  222,    0,
      255,    0,   88,  132,   22,  158,  284,    0,  926,  927,
        3,  922,  921,  927,  901,  895,  892,  896,  903,  898,
       19,  888,  900,   81,  880,  897,  881,  885,  881,  880,
       27,  879,  875,  878,    0,   58,  871,   33,   14,   56,
      884,  884,   97,   43,  887,  870,  867,  879,  869,  862,
      868,  864,  875,    6,  870,  869,  860,   51,   62,    0,
       11,  888,  927,  175,    0,    0,  927,  876,  194,  927,
       71,  116,    7,  122,  127,  256,  267,    3,  264,  287,

      281,  875,  188,  129,  167,   93,  147,  179,  295,  299,
      253,  213,  885,  884,  927,  864,  850,  866,  850,  848,
      844,  851,  863,  839,  845,  852,  848,  838,  841,  844,
      927,  841,  837,  847,  833,  838,  836,  927,  841,  830,
      314,  829,  927,  249,  844,  827,  248,  841,  828,  820,
      838,  155,  927,  824,  311,  288,  827,  826,  927,  821,
      828,  835,  816,  814,  828,  813,  826,  812,  312,  827,
      809,  813,  811,  809,  808,  807,  813,    0,  329,  331,
      927,  822,  202,  328,  330,  321,  329,  288,  821,  333,
      337,  338,  335,  339,  341,  342,  345,   85,  346,  347,

      350,  349,  353,  354,  358,  125,  357,  360,  368,  359,
      378,  377,  366,  381,  367,  384,  802,  800,  805,  797,
      812,  797,  809,  793,  811,  808,  797,  803,  812,  784,
      789,  788,  798,  927,  783,  797,  784,  785,  783,  792,
      779,  927,  784,  927,  778,  779,  927,  783,  782,  781,
      785,  779,  784,  771,  781,  767,  779,  769,  776,  771,
      760,  759,  772,  762,  758,  769,  767,  767,  756,  766,
      756,  760,  762,  747,  927,  760,  927,  741,    0,  385,
      376,  388,  387,  392,  764,  393,  394,  395,  396,  763,
      399,  397,  762,  400,  402,  761,  401,  760,  409,  405,

        0,  412,  415,  418,  759,  419,  420,  421,  758,  424,
      751,  736,  734,  748,  744,  742,  927,  741,  734,  733,
      732,  927,  745,  744,  744,  927,  927,  738,  927,  927,
      735,  927,  724,  739,  734,  718,  718,  719,  722,  733,
      721,  719,  726,  716,  927,  710,  723,  726,  708,  724,
      719,  714,  705,  702,  696,  702,  709,  698,  702,  927,
      706,  927,  701,  698,  927,  927,  713,  430,  426,  423,
      712,  427,  428,  431,  434,  436,  711,  445,  446,  449,
      710,  450,  451,  709,  454,  452,  708,  455,  456,  458,
      460,  699,  700,  700,  689,  927,  683,  683,  694,  685,

      677,  697,  679,  689,  927,  927,  927,  687,  674,  673,
      927,  686,  670,  675,  683,  667,  672,  681,  927,  663,
      666,  663,  667,  927,  662,  927,  674,  927,  657,  654,
      927,  672,  656,  659,  927,  474,  261,  462,  471,  467,
      674,  673,  469,  476,  478,  480,  482,  487,  484,  672,
      488,  671,  670,  669,  489,  492,  666,  649,  660,  927,
      659,  644,  927,  662,  656,  657,  655,  644,  652,  927,
      651,  927,  642,  927,  927,  641,  634,  634,  927,  627,
      649,  646,  629,  630,  645,  927,  627,  927,  640,  494,
      493,  495,  498,  500,  644,  643,  496,  505,  506,  642,

      507,  641,  508,  620,  927,  927,  927,  629,  634,  619,
      627,  927,  613,  927,  927,  927,  927,  624,  927,  927,
      619,  626,  621,  611,  616,  927,  622,  512,  516,  627,
      511,  518,  626,  519,  523,  528,  529,  619,  613,  600,
      927,  927,  612,  577,  572,  927,  584,  927,  927,  927,
      530,  533,  587,  535,  537,  520,  586,  531,  927,  566,
      927,  582,  577,  927,  563,  581,  539,  543,  552,  579,
      578,  927,  575,  560,  927,  544,  546,  558,  569,  570,
      550,  294,  560,  548,  198,  569,  570,  927,  171,  562,
      571,   56,  927,  605,  610,  615,  620,  624,  629,  631,

      633
    } ;

static const flex_int16_t yy_def[602] =
    {   0,
      594,  594,    2,    3,    3,    5,    3,    3,    3,    9,
        3,    3,    9,   13,    3,   15,  595,  595,  593,   19,
       19,   21,   21,   21,   21,   21,   21,   27,  593,  593,
      593,  593,  596,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  597,
      597,  593,  593,  598,  597,  599,  593,  600,  600,  593,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,

      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  593,  593,  596,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  597,  597,  598,
      593,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,

      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  601,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,

      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  601,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  593,  593,  593,  593,  593,  593,  593,  593,  593,

      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  601,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,

      600,  600,  600,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      600,  600,  600,  600,  600,  600,  600,  600,  593,  593,
      593,  593,  593,  593,  593,  600,  600,  600,  600,  600,
      600,  593,  593,  593,  593,  600,  600,  600,  593,  593,
      600,  600,  600,  600,  593,  600,  600,  593,  600,  600,
      600,  600,    0,  593,  593,  593,  593,  593,  593,  593,

      593
    } ;

static const flex_int16_t yy_nxt[968] =
    {   0,
      593,   31,   32,   31,  112,   33,  112,  593,  141,  141,
      141,   34,  179,  183,  179,   35,  183,   36,  384,   30,
      183,   30,  194,   37,   30,  169,   38,   39,   30,   88,
       30,   40,   41,   31,   32,   31,   67,   33,  122,   30,
      170,   30,  148,   34,   30,  187,  136,   35,   30,   36,
       30,  149,  123,   88,   88,   37,   67,   88,   38,   39,
      137,  146,  147,   40,   41,   42,  158,   43,  174,  183,
       44,  150,  159,   30,   45,  151,   46,   30,  142,  152,
      176,   30,   30,   30,  183,   30,   47,   48,   30,  175,
      177,  143,   30,  144,   49,   88,  126,  185,  183,   50,

       51,   52,   53,   30,  127,   30,  183,  106,   30,  128,
      129,   54,   30,   30,   30,   30,  155,  292,   30,   88,
       88,   54,   30,   88,   30,   55,   55,   55,  209,  183,
      156,  157,   56,   57,   58,  183,   59,   30,  183,   88,
      183,   30,  183,   30,   60,  186,   61,   62,  207,   63,
       64,  106,   65,   66,   68,   30,   69,  189,   70,  300,
      183,  188,   71,   88,   88,   88,   30,   88,   30,   72,
       73,   74,   30,  251,   30,   75,   30,  115,   30,  114,
      183,   30,  208,  252,  183,   30,  210,   76,  114,   88,
       88,   77,  183,   88,   78,   79,   81,   82,   81,   83,

       84,  183,  184,  184,  184,  279,   85,  183,   86,   81,
       82,   81,   83,   84,  112,  183,  112,  206,  211,   85,
      588,   86,   30,   31,   32,   31,   87,   33,   88,   88,
       89,   89,   89,   34,   90,   88,   88,   88,   91,   92,
       93,   88,   88,   94,   88,   95,   88,   88,   96,   88,
       88,   88,   97,   98,   99,  100,  101,   88,   88,   88,
       88,   88,  102,   88,   88,   88,  183,   30,  241,  183,
      242,   88,   88,   88,  183,  245,   88,  183,   88,  190,
      183,   88,  246,  490,  216,   88,  103,  104,   88,   88,
      105,   88,  195,  192,  183,  191,  196,  197,  193,  204,

      183,  183,  198,  256,  199,  107,  257,  183,  183,  200,
      108,  283,  183,  205,  109,   88,  110,  111,  201,   88,
      202,  212,  141,  141,  141,  203,  213,  214,  254,  269,
      179,  215,  179,  115,  183,  114,  184,  184,  184,  255,
      270,  183,  183,  183,  114,  280,  183,  285,  183,  281,
      183,  183,  183,  286,  183,  183,  289,  282,  183,  183,
      183,  284,  183,  183,  287,  295,  183,  183,  290,  288,
      183,  183,  183,  183,  291,  296,  293,  299,  294,  183,
      183,  183,  304,  297,  298,  301,  302,  303,  305,  183,
      183,  183,  306,  309,  183,  307,  308,  183,  183,  310,

      183,  183,  368,  370,  369,  183,  183,  183,  183,  183,
      183,  372,  183,  183,  183,  183,  373,  371,  183,  379,
      381,  375,  183,  378,  382,  183,  376,  374,  183,  377,
      380,  183,  183,  183,  183,  385,  183,  183,  383,  183,
      183,  183,  388,  183,  183,  438,  386,  183,  387,  183,
      439,  390,  391,  389,  440,  437,  441,  443,  183,  183,
      442,  446,  183,  183,  183,  183,  444,  183,  183,  183,
      450,  183,  451,  183,  445,  183,  449,  279,  447,  491,
      183,  448,  183,  453,  183,  454,  494,  436,  455,  183,
      452,  183,  456,  183,  492,  183,  493,  183,  497,  496,

      183,  183,  183,  501,  498,  183,  183,  183,  183,  183,
      500,  183,  530,  183,  495,  532,  531,  499,  183,  183,
      183,  183,  503,  528,  183,  183,  529,  502,  533,  183,
      553,  183,  183,  183,  534,  535,  183,  537,  551,  552,
      536,  183,  183,  183,  183,  555,  183,  557,  183,  566,
      183,  554,  183,  570,  556,  569,  183,  183,  568,  183,
      558,  183,  567,  183,  571,  183,  578,  576,  580,  580,
      580,  183,  577,  183,  582,  183,  581,  583,  580,  580,
      580,  587,  183,  183,  183,  590,  585,  589,  586,  579,
      584,  183,  183,  591,  183,  575,  574,  573,  572,  183,

      183,  565,  564,  563,  592,   30,   30,   30,   30,   30,
       80,   80,   80,   80,   80,  114,  114,  114,  114,  114,
      178,  562,  561,  178,  180,  180,  180,  180,  180,  181,
      560,  181,  181,  181,  182,  182,  367,  367,  559,  183,
      183,  550,  549,  548,  547,  546,  545,  544,  543,  542,
      541,  540,  539,  538,  183,  183,  183,  183,  527,  526,
      525,  524,  523,  522,  521,  520,  519,  518,  517,  516,
      515,  514,  513,  512,  511,  510,  509,  508,  507,  506,
      505,  504,  183,  183,  183,  183,  183,  183,  489,  488,
      487,  486,  485,  484,  483,  482,  481,  480,  479,  478,

      477,  476,  475,  474,  473,  472,  471,  470,  469,  468,
      467,  466,  465,  464,  463,  462,  461,  460,  459,  458,
      457,  183,  183,  183,  183,  183,  436,  435,  434,  433,
      432,  431,  430,  429,  428,  427,  426,  425,  424,  423,
      422,  421,  420,  419,  418,  417,  416,  415,  414,  413,
      412,  411,  410,  409,  408,  407,  406,  405,  404,  403,
      402,  401,  400,  399,  398,  397,  396,  395,  394,  393,
      392,  183,  183,  183,  183,  183,  183,  183,  366,  365,
      364,  363,  362,  361,  360,  359,  358,  357,  356,  355,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,

      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,
      314,  313,  312,  311,  183,  183,  278,  277,  276,  275,
      274,  273,  272,  271,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  253,  250,  249,  248,  247,
      244,  243,  240,  239,  238,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  115,  113,  183,  183,
      113,  173,  172,  171,  168,  167,  166,  165,  164,  163,

      162,  161,  160,  154,  153,  145,  140,  139,  138,  135,
      134,  133,  132,  131,  130,  125,  124,  121,  120,  119,
      118,  117,  116,  115,  113,  593,   29,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593
    } ;

static const flex_int16_t yy_chk[968] =
    {   0,
        0,    1,    1,    1,   31,    1,   31,    0,   55,   55,
       55,    1,   81,  301,   81,    1,   98,    1,  301,   11,
       93,   11,   98,    1,   11,   74,    1,    1,   11,   25,
       11,    1,    1,    2,    2,    2,   11,    2,   41,   12,
       74,   12,   59,    2,   12,   93,   51,    2,   12,    2,
       12,   59,   41,   25,   25,    2,   12,   25,    2,    2,
       51,   58,   58,    2,    2,    3,   64,    3,   78,  592,
        3,   60,   64,    3,    3,   60,    3,    3,   56,   60,
       79,    3,    3,    5,   91,    5,    5,    5,    5,   78,
       79,   56,    5,   56,    5,   23,   44,   91,  198,    5,

        5,    5,    5,    7,   44,    7,  106,   23,    7,   44,
       44,    7,    7,    8,    7,    8,   63,  198,    8,   23,
       23,    8,    8,   23,    8,    9,    9,    9,  106,   92,
       63,   63,    9,    9,    9,   94,    9,    9,  206,   24,
       95,    9,  104,    9,    9,   92,    9,    9,  104,    9,
        9,   24,    9,    9,   13,   13,   13,   95,   13,  206,
      107,   94,   13,   24,   24,   26,   13,   24,   13,   13,
       13,   13,   13,  152,   13,   13,   15,   84,   15,   84,
      105,   15,  105,  152,  589,   15,  107,   15,   84,   26,
       26,   15,  108,   26,   15,   15,   17,   17,   17,   17,

       17,  103,   89,   89,   89,  183,   17,   89,   17,   18,
       18,   18,   18,   18,  112,  183,  112,  103,  108,   18,
      585,   18,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   21,   21,   21,   21,  111,   21,  144,   96,
      144,   21,   21,   21,  437,  147,   21,   99,   21,   96,
       97,   21,  147,  437,  111,   21,   21,   21,   21,   21,
       21,   27,   99,   97,  101,   96,   99,   99,   97,  101,

      100,  188,   99,  156,  100,   27,  156,  582,  109,  100,
       27,  188,  110,  101,   27,   27,   27,   27,  100,   27,
      100,  109,  141,  141,  141,  100,  109,  110,  155,  169,
      179,  110,  179,  180,  186,  180,  184,  184,  184,  155,
      169,  184,  187,  185,  180,  185,  190,  191,  193,  186,
      191,  192,  194,  192,  195,  196,  195,  187,  197,  199,
      200,  190,  202,  201,  193,  201,  203,  204,  196,  194,
      207,  205,  210,  208,  197,  202,  199,  205,  200,  213,
      215,  209,  210,  203,  204,  207,  208,  209,  211,  281,
      212,  211,  212,  215,  214,  213,  214,  216,  280,  216,

      283,  282,  280,  282,  281,  284,  286,  287,  288,  289,
      292,  284,  291,  294,  297,  295,  286,  283,  300,  294,
      297,  288,  299,  292,  299,  302,  289,  287,  303,  291,
      295,  304,  306,  307,  308,  302,  370,  310,  300,  369,
      372,  373,  306,  368,  374,  369,  303,  375,  304,  376,
      370,  308,  310,  307,  372,  368,  373,  375,  378,  379,
      374,  379,  380,  382,  383,  386,  376,  385,  388,  389,
      383,  390,  385,  391,  378,  438,  382,  436,  379,  438,
      440,  380,  443,  388,  439,  389,  443,  436,  390,  444,
      386,  445,  391,  446,  439,  447,  440,  449,  446,  445,

      448,  451,  455,  451,  447,  456,  491,  490,  492,  497,
      449,  493,  492,  494,  444,  494,  493,  448,  498,  499,
      501,  503,  456,  490,  531,  528,  491,  455,  497,  529,
      531,  532,  534,  556,  498,  499,  535,  503,  528,  529,
      501,  536,  537,  551,  558,  534,  552,  536,  554,  551,
      555,  532,  567,  556,  535,  555,  568,  576,  554,  577,
      537,  584,  552,  581,  558,  569,  569,  567,  574,  574,
      574,  578,  568,  583,  577,  590,  576,  578,  580,  580,
      580,  584,  586,  587,  591,  587,  579,  586,  583,  573,
      578,  571,  570,  590,  566,  565,  563,  562,  560,  557,

      553,  547,  545,  544,  591,  594,  594,  594,  594,  594,
      595,  595,  595,  595,  595,  596,  596,  596,  596,  596,
      597,  543,  540,  597,  598,  598,  598,  598,  598,  599,
      539,  599,  599,  599,  600,  600,  601,  601,  538,  533,
      530,  527,  525,  524,  523,  522,  521,  518,  513,  511,
      510,  509,  508,  504,  502,  500,  496,  495,  489,  487,
      485,  484,  483,  482,  481,  480,  478,  477,  476,  473,
      471,  469,  468,  467,  466,  465,  464,  462,  461,  459,
      458,  457,  454,  453,  452,  450,  442,  441,  434,  433,
      432,  430,  429,  427,  425,  423,  422,  421,  420,  418,

      417,  416,  415,  414,  413,  412,  410,  409,  408,  404,
      403,  402,  401,  400,  399,  398,  397,  395,  394,  393,
      392,  387,  384,  381,  377,  371,  367,  364,  363,  361,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      349,  348,  347,  346,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  333,  331,  328,  325,  324,
      323,  321,  320,  319,  318,  316,  315,  314,  313,  312,
      311,  309,  305,  298,  296,  293,  290,  285,  278,  276,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,

      254,  253,  252,  251,  250,  249,  248,  246,  245,  243,
      241,  240,  239,  238,  237,  236,  235,  233,  232,  231,
      230,  229,  228,  227,  226,  225,  224,  223,  222,  221,
      220,  219,  218,  217,  189,  182,  177,  176,  175,  174,
      173,  172,  171,  170,  168,  167,  166,  165,  164,  163,
      162,  161,  160,  158,  157,  154,  151,  150,  149,  148,
      146,  145,  142,  140,  139,  137,  136,  135,  134,  133,
      132,  130,  129,  128,  127,  126,  125,  124,  123,  122,
      121,  120,  119,  118,  117,  116,  114,  113,  102,   88,
       82,   77,   76,   75,   73,   72,   71,   70,   69,   68,

       67,   66,   65,   62,   61,   57,   54,   53,   52,   50,
       49,   48,   47,   46,   45,   43,   42,   40,   39,   38,
       37,   36,   35,   33,   32,   29,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[116] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "conffile.l"
#line 2 "conffile.l"
#include "allocator.h"
#include "conffile.h"
#include "conffile.tab.h"
#define YYSTYPE ROUTER_YYSTYPE

#define YY_DECL int router_yylex \
	(YYSTYPE *yylval_param, ROUTER_YYLTYPE *llocp, yyscan_t yyscanner, router *rtr, allocator *ralloc, allocator *palloc)
#define YY_USER_ACTION llocp->first_line = llocp->last_line = yylineno; \
	llocp->first_column = yycolumn; llocp->last_column = yycolumn+yyleng-1; \
	yycolumn += yyleng;
#define YY_USER_INIT yycolumn = 0; yylineno = 0;

int identstate = 0;
#line 1096 "conffile.yy.c"
#define YY_NO_INPUT 1

#line 1099 "conffile.yy.c"

#define INITIAL 0
#define cl 1
#define ma 2
#define re 3
#define ag 4
#define se 5
#define st 6
#define li 7
#define qu 8
#define idcl 9
#define idma 10
#define idag 11
#define idin 12
#define idli 13

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 31 "conffile.l"


#line 34 "conffile.l"
	char string_buf[1024];
	char *strbuf = NULL;

#line 1391 "conffile.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 594 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 927 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "conffile.l"
{
						identstate = cl;
						BEGIN(idcl);
						return crCLUSTER;
					}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 42 "conffile.l"
{
						identstate = idcl;
						BEGIN(idcl);
						return crFORWARD;
					}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 47 "conffile.l"
{
						identstate = idcl;
						BEGIN(idcl);
						return crANY_OF;
					}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "conffile.l"
{
						identstate = idcl;
						BEGIN(idcl);
						return crFAILOVER;
					}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 57 "conffile.l"
{
						identstate = idcl;
						BEGIN(idcl);
						return crLB;
					}					
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "conffile.l"
return crUSEALL;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "conffile.l"
{
						identstate = idcl;
						BEGIN(idcl);
						return crCARBON_CH;
					}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "conffile.l"
{
						identstate = idcl;
						BEGIN(idcl);
						return crFNV1A_CH;
					}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 73 "conffile.l"
{
						identstate = idcl;
						BEGIN(idcl);
						return crJUMP_FNV1A_CH;
					}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 78 "conffile.l"
return crREPLICATION;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 79 "conffile.l"
return crDYNAMIC;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 80 "conffile.l"
{
						identstate = idcl;
						BEGIN(idcl);
						return crFILE;
					}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 85 "conffile.l"
return crIP;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 86 "conffile.l"
return crPROTO;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 87 "conffile.l"
return crUDP;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 88 "conffile.l"
return crTCP;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 89 "conffile.l"
return crTYPE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 90 "conffile.l"
return crLINEMODE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 91 "conffile.l"
return crSYSLOGMODE;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 92 "conffile.l"
return crTRANSPORT;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 93 "conffile.l"
return crPLAIN;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 94 "conffile.l"
return crGZIP;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 95 "conffile.l"
return crLZ4;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 96 "conffile.l"
return crSNAPPY;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 97 "conffile.l"
return crSSL;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 98 "conffile.l"
return '=';
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 99 "conffile.l"
return crCONNECTIONS;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 100 "conffile.l"
return crTHRESHOLD_START;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 101 "conffile.l"
return crTHRESHOLD_END;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 102 "conffile.l"
return crTTL;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 103 "conffile.l"
return crTHREADS;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 104 "conffile.l"
{
						identstate = idma;
						BEGIN(idma);
						return crMATCH;
					}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 109 "conffile.l"
return '*';
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 110 "conffile.l"
{
						identstate = ma;
						BEGIN(idma);
						return crVALIDATE;
					}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 115 "conffile.l"
return crELSE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 116 "conffile.l"
return crLOG;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 117 "conffile.l"
return crDROP;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 118 "conffile.l"
{
						BEGIN(ma);
						return crROUTE;
					}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 122 "conffile.l"
{	
						identstate = ma;
						BEGIN(idma);
						return crUSING;
					}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 127 "conffile.l"
{
						BEGIN(ma);
						return crSEND;
					}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 131 "conffile.l"
{
						identstate = idcl;
						BEGIN(idcl);
						return crTO;
					}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 136 "conffile.l"
return crBLACKHOLE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 137 "conffile.l"
return crSTOP;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 139 "conffile.l"
{
						identstate = re;
						BEGIN(idma);
						return crREWRITE;
					}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 144 "conffile.l"
{
						identstate = re;
						BEGIN(idma);
						return crINTO;
					}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 150 "conffile.l"
{
						identstate = idag;
						BEGIN(idag);
						return crAGGREGATE;
					}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 155 "conffile.l"
{
						BEGIN(ag);
						return crEVERY;
					}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 159 "conffile.l"
return crSECONDS;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 160 "conffile.l"
return crEXPIRE;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 161 "conffile.l"
return crAFTER;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 162 "conffile.l"
return crTIMESTAMP;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 163 "conffile.l"
return crAT;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 164 "conffile.l"
return crSTART;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 165 "conffile.l"
return crMIDDLE;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 166 "conffile.l"
return crEND;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 167 "conffile.l"
return crOF;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 168 "conffile.l"
return crBUCKET;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 169 "conffile.l"
return crCOMPUTE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 170 "conffile.l"
return crSUM;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 171 "conffile.l"
return crSUM;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 172 "conffile.l"
return crCOUNT;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 173 "conffile.l"
return crCOUNT;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 174 "conffile.l"
return crMAX;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 175 "conffile.l"
return crMAX;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 176 "conffile.l"
return crMIN;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 177 "conffile.l"
return crMIN;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 178 "conffile.l"
return crAVERAGE;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 179 "conffile.l"
return crAVERAGE;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 180 "conffile.l"
return crMEDIAN;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 181 "conffile.l"
{
						yylval_param->crINTVAL =
							atoi(yytext + strlen("percentile"));
						return crPERCENTILE;
					}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 186 "conffile.l"
return crVARIANCE;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 187 "conffile.l"
return crSTDDEV;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 188 "conffile.l"
return crWRITE;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 189 "conffile.l"
{
						identstate = ag;
						BEGIN(idag);
						return crTO;
					}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 194 "conffile.l"
{
						/* reuse the match logic for send to ... stop */
						BEGIN(ma);
						return crSEND;
					}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 200 "conffile.l"
{
						BEGIN(se);
						return crSEND;
					}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 204 "conffile.l"
{
						/* reuse the match logic for send to ... stop */
						BEGIN(ma);
						return crSTATISTICS;
					}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 210 "conffile.l"
{
						BEGIN(st);
						return crSTATISTICS;
					}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 214 "conffile.l"
return crSUBMIT;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 215 "conffile.l"
return crEVERY;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 216 "conffile.l"
return crSECONDS;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 217 "conffile.l"
return crRESET;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 218 "conffile.l"
return crCOUNTERS;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 219 "conffile.l"
return crAFTER;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 220 "conffile.l"
return crINTERVAL;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 221 "conffile.l"
return crPREFIX;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 222 "conffile.l"
{
						identstate = st;
						BEGIN(idag);
						return crWITH;
					}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 227 "conffile.l"
{
						/* reuse the match logic for send to ... stop */
						BEGIN(ma);
						return crSEND;
					}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 233 "conffile.l"
{
						BEGIN(li);
						return crLISTEN;
					}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 237 "conffile.l"
return crTYPE;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 238 "conffile.l"
{
						identstate = li;
						BEGIN(idli);
						return crLINEMODE;
					}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 243 "conffile.l"
return crTRANSPORT;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 244 "conffile.l"
return crPLAIN;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 245 "conffile.l"
{
						identstate = li;
						BEGIN(idli);
						return crGZIP;
					}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 250 "conffile.l"
{
						identstate = li;
						BEGIN(idli);
						return crLZ4;
					}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 255 "conffile.l"
{
						identstate = li;
						BEGIN(idli);
						return crSNAPPY;
					}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 260 "conffile.l"
{
						identstate = idli;
						BEGIN(idli);
						return crSSL;
					}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 265 "conffile.l"
{
						BEGIN(li);
						return crPROTO;
					}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 269 "conffile.l"
{
						identstate = li;
						BEGIN(idli);
						return crUDP;
					}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 274 "conffile.l"
{
						identstate = li;
						BEGIN(idli);
						return crTCP;
					}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 279 "conffile.l"
{
						identstate = li;
						BEGIN(idli);
						return crUNIX;
					}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 285 "conffile.l"
{
						identstate = INITIAL;
						BEGIN(idin);
						return crINCLUDE;
					}
	YY_BREAK
/* handle quoted strings */
case 103:
YY_RULE_SETUP
#line 292 "conffile.l"
{
						strbuf = string_buf;
						BEGIN(qu);
					}
	YY_BREAK

case 104:
YY_RULE_SETUP
#line 297 "conffile.l"
{
						if (strbuf == string_buf) {
							router_yyerror(llocp, NULL, rtr, ralloc, palloc,
									"empty string");
							yyterminate();
						}
						BEGIN(identstate);
						*strbuf = '\0';
						yylval_param->crSTRING = ra_strdup(palloc, string_buf);
						return crSTRING;
					}
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 308 "conffile.l"
{
						router_yyerror(llocp, NULL, rtr, ralloc, palloc,
								"unterminated string");
						yyterminate();
					}
	YY_BREAK
case YY_STATE_EOF(qu):
#line 313 "conffile.l"
{
						router_yyerror(llocp, NULL, rtr, ralloc, palloc,
								"unterminated string");
						yyterminate();
					}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 318 "conffile.l"
{
						*strbuf++ = yytext[1];
						if (strbuf == string_buf + sizeof(string_buf)) {
							router_yyerror(llocp, NULL, rtr, ralloc, palloc,
									"string too large");
							yyterminate();
						}
					}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 326 "conffile.l"
{
						char *yptr = yytext;
						while (*yptr) {
							*strbuf++ = *yptr++;
							if (strbuf == string_buf + sizeof(string_buf)) {
								router_yyerror(llocp, NULL, rtr,
										ralloc, palloc, "string too large");
								yyterminate();
							}
						}
					}
	YY_BREAK

case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 339 "conffile.l"
{
						/* ignore for now
						yylval_param->crCOMMENT = ra_strdup(palloc, yytext);
						return crCOMMENT;
						*/
						yycolumn = 0;
						;
					}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 348 "conffile.l"
; /* whitespace */
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 349 "conffile.l"
yycolumn = 0;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 350 "conffile.l"
{
						yylval_param->crINTVAL = atoi(yytext);
						return crINTVAL;
					}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 354 "conffile.l"
{
						yylval_param->crSTRING = ra_strdup(palloc, yytext);
						BEGIN(identstate);
						return crSTRING;
					}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 359 "conffile.l"
{ BEGIN(INITIAL); return ';'; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 360 "conffile.l"
{
						/* feed this back to the parser, it will give a
						 * nice error message */
						yylval_param->crSTRING = ra_strdup(palloc, yytext);
						return crUNEXPECTED;
					}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 367 "conffile.l"
ECHO;
	YY_BREAK
#line 2247 "conffile.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(cl):
case YY_STATE_EOF(ma):
case YY_STATE_EOF(re):
case YY_STATE_EOF(ag):
case YY_STATE_EOF(se):
case YY_STATE_EOF(st):
case YY_STATE_EOF(li):
case YY_STATE_EOF(idcl):
case YY_STATE_EOF(idma):
case YY_STATE_EOF(idag):
case YY_STATE_EOF(idin):
case YY_STATE_EOF(idli):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 594 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 594 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 593);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	if ( c == '\n' )
		
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 367 "conffile.l"


